AWSTemplateFormatVersion: "2010-09-09"
Description: Glue ETL base infrastructure

Parameters:
  ProjectName:
    Type: String
    Default: aws-glue-etl

Resources:

  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-raw-${AWS::AccountId}"

  CuratedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-curated-${AWS::AccountId}"

  RawGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: raw_db

  CuratedGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: curated_db

  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-glue-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueBasePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:CreateTable
                  - glue:UpdateTable
                Resource: "*"
  RawCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: raw-s3-crawler
      Role: !GetAtt GlueExecutionRole.Arn
      DatabaseName: raw_db
      Targets:
        S3Targets:
          - Path: !Sub "s3://${RawBucket}"
      SchemaChangePolicy:
        UpdateBehavior: LOG
        DeleteBehavior: LOG
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_NEW_FOLDERS_ONLY
      TablePrefix: raw_
  RawToCuratedGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: raw-to-curated-job
      Role: !GetAtt GlueExecutionRole.Arn
      GlueVersion: "4.0"
      NumberOfWorkers: 2
      WorkerType: G.1X
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub "s3://${RawBucket}/scripts/raw_to_curated.py"
      DefaultArguments:
        "--job-language": "python"
        "--enable-metrics": "true"
        "--enable-continuous-cloudwatch-log": "true"
        "--SOURCE_DB": "raw_db"
        "--SOURCE_TABLE": "raw_aws_glue_etl_raw_446072489762"
        "--TARGET_S3_PATH": !Sub "s3://${CuratedBucket}/games/"
      MaxRetries: 1
      Timeout: 10
