name: Deploy Glue ETL Stack

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::446072489762:role/GitHubActionsCloudFormationRole
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name aws-glue-etl \
            --template-file cloudformation/etl-stack.yaml \
            --capabilities CAPABILITY_NAMED_IAM
